POST localhost:8080/apprentice
content-type:application/json

{
  "surname" : "Kryldov",
  "name" : "Chdigik",
  "patronymic" : "Yafychev",
  "phoneNumber" : "829722724931"

}

###
POST localhost:8080/trainer
content-type:application/json

{
  "surname" : "1234",
  "name" : "dddd",
  "patronymic" : "ddd",
  "experience" : 2

}


###
GET localhost:8080/user/1

###
DELETE localhost:8080/user/3