POST localhost:8080/user
content-type:application/json

{
  "login" : "admin",
  "password" : "admin",
  "name" : "Main Admin"

}
###
POST localhost:8080/user
content-type:application/json

{
  "login" : "qwer",
  "password" : "1234",
  "name" : "Admin"

}

###
GET localhost:8080/user?login=admin&password=admin
###
GET localhost:8080/user?login=qwerty&password=123
###
GET localhost:8080/user/1
###
DELETE localhost:8080/user/1

###
POST localhost:8080/apprentice
content-type:application/json

{
  "surname" : "Ivanov",
  "name" : "Ivan",
  "patronymic" : "Ivanovich",
  "phoneNumber" : "89199999999"

}

###
POST localhost:8080/apprentice
content-type:application/json

{
  "surname" : "Sidorov",
  "name" : "Evgen",
  "patronymic" : "Evgnevich",
  "phoneNumber" : "89192939999"

}
###
POST localhost:8080/apprentice
content-type:application/json

{
"surname" : "Leontev",
"name" : "Alex",
"patronymic" : "Dguzepovich",
"phoneNumber" : "89132939999"

}

###
POST localhost:8080/apprentice
content-type:application/json

{
  "surname" : "Bykov",
  "name" : "Markiz",
  "patronymic" : "Olegovich",
  "phoneNumber" : "89132944993"

}
###
POST localhost:8080/apprentice
content-type:application/json

{
  "surname" : "Zykov",
  "name" : "Mixail",
  "patronymic" : "Krotovicn",
  "phoneNumber" : "89142224997"

}
###
POST localhost:8080/apprentice
content-type:application/json

{
"surname" : "Mavrin",
"name" : "Ura",
"patronymic" : "Piratovich",
"phoneNumber" : "89142424997"

}
###
POST localhost:8080/apprentice
content-type:application/json

{
  "surname" : "Oborin",
  "name" : "Jack",
  "patronymic" : "Krukovich",
  "phoneNumber" : "83942424933"

}
###
POST localhost:8080/apprentice
content-type:application/json

{
  "surname" : "Kipelov",
  "name" : "Valeriy",
  "patronymic" : "Krukovich",
  "phoneNumber" : "83942421111"

}

###
POST localhost:8080/apprentice
content-type:application/json

{
  "surname" : "Sharikov",
  "name" : "Sharik",
  "patronymic" : "Pryamougolnikovich",
  "phoneNumber" : "84942524433"

}

###
POST localhost:8080/apprentice
content-type:application/json

{
  "surname" : "Zuzyf",
  "name" : "Vano",
  "patronymic" : "Provodovich",
  "phoneNumber" : "83977724933"

}
###
POST localhost:8080/apprentice
content-type:application/json

{
  "surname" : "Krylov",
  "name" : "Chigik",
  "patronymic" : "Yaychev",
  "phoneNumber" : "82977724931"

}

###
PUT localhost:8080/apprentice
content-type:application/json

{
  "id": 6,
  "surname" : "Ivanov",
  "name" : "Ivan",
  "patronymic" : "Ivanovich",
  "phoneNumber" : "89199999991"

}

###
DELETE localhost:8080/apprentice/4

###
POST localhost:8080/trainer
content-type:application/json

{
  "surname" : "Ivanov",
  "name" : "Ivan",
  "patronymic" : "Ivanovich",
  "experience" : 25

}
###
POST localhost:8080/trainer
content-type:application/json

{
  "surname" : "Manson",
  "name" : "Marlin",
  "patronymic" : "Pupkin",
  "experience" : 13

}
###
POST localhost:8080/trainer
content-type:application/json

{
"surname" : "Petrov",
"name" : "Petr",
"patronymic" : "Petrovich",
"experience" : 1

}

###
POST localhost:8080/trainer
content-type:application/json

{
  "surname" : "Nikitin",
  "name" : "Nik",
  "patronymic" : "Petrovich",
  "experience" : 2

}

###
POST localhost:8080/trainer
content-type:application/json

{
  "surname" : "Bobrov",
  "name" : "Bobr",
  "patronymic" : "Zubatovich",
  "experience" : 12

}


###
PUT localhost:8080/trainer
content-type:application/json

{
  "id": 2,
  "surname" : "Ivanov",
  "name" : "Ivan",
  "patronymic" : "Ivanovich",
  "experience" : 27

}


###
DELETE localhost:8080/trainer/1

###
POST localhost:8080/schedule/1?dayWeek=monday&start=10:00&end=12:00

###
POST localhost:8080/schedule/2?dayWeek=monday&start=10:00&end=12:00

###
POST localhost:8080/schedule/3?dayWeek=monday&start=10:00&end=12:00

###
POST localhost:8080/schedule/1?dayWeek=tuesday&start=14:00&end=16:00
###
POST localhost:8080/schedule/2?dayWeek=monday&start=09:00&end=17:00

###
POST localhost:8080/schedule/6?dayWeek=monday&start=09:00&end=17:00

###
POST localhost:8080/schedule/120?dayWeek=monday&start=09:00&end=18:00

###
GET localhost:8080/schedule/1

###
PUT localhost:8080/schedule/1/update?dayWeek=monday&start=09:00&end=17:00
###
DELETE localhost:8080/schedule/11?day=monday

###
POST localhost:8080/training?idTrainer=1&idApprentice=2&numberGym=1&date=2023-12-25&startTime=09:00

###
POST localhost:8080/training?idTrainer=1&idApprentice=5&numberGym=1&date=2023-12-25&startTime=09:00

###
POST localhost:8080/training?idTrainer=6&idApprentice=15&numberGym=1&date=2023-12-25&startTime=09:00
###
POST localhost:8080/training?idTrainer=1&idApprentice=5&numberGym=1&date=2023-12-25&startTime=09:00
###
POST localhost:8080/training?idTrainer=1&idApprentice=5&numberGym=1&date=2023-12-25&startTime=09:00

###
GET  localhost:8080/training?idTrainer=1&date=2024-01-08&numberGym=1

















###
POST localhost:8080/training?idTrainer=3&idApprentice=1&numberGym=1&date=2023-12-25&startTime=09:00
###
POST localhost:8080/training?idTrainer=1&idApprentice=4&numberGym=1&date=2023-12-25&startTime=12:30
###
POST localhost:8080/training?idTrainer=3&idApprentice=9&numberGym=1&date=2023-12-25&startTime=09:00
###
DELETE localhost:8080/training/14
###
GET localhost:8080/training/apprentice/1
###
GET localhost:8080/training/trainer/2